name: chat_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.5
  image_picker: ^1.1.2
  intl: ^0.20.2
  just_audio: ^0.9.46
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  video_player: ^2.9.3
  waveform_recorder: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Thin-100.ttf
        - asset: assets/fonts/Gilroy-UltraLight-200.ttf
        - asset: assets/fonts/Gilroy-Light-300.ttf
        - asset: assets/fonts/Gilroy-Regular-normal.ttf
        - asset: assets/fonts/Gilroy-Medium-500.ttf
        - asset: assets/fonts/Gilroy-Semibold-600.ttf
        - asset: assets/fonts/Gilroy-Bold-bold.ttf
        - asset: assets/fonts/Gilroy-Extrabold-800.ttf
        - asset: assets/fonts/Gilroy-Heavy-900.ttf
        - asset: assets/fonts/Gilroy-Black-900.ttf
